connector:
    name: oro_importexport
    jobs:
        mock_data_import_categories:
            title: "Import categories from mock data JSON server"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader: Demo\Bundle\MockDataIntegrationBundle\Connector\CategoryConnector
                        processor: oro_importexport.processor.import_delegate
                        writer: oro_catalog.importexport.writer.category

        mock_data_export_categories:
            title: "Export categories to mock data JSON server"
            type: export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader: oro_integration.reader.entity.by_id
                        processor: oro_importexport.processor.export_delegate
                        writer: Demo\Bundle\MockDataIntegrationBundle\ImportExport\Writer\CategoryExportWriter
